import asyncio
import json
import uuid
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional
from enum import Enum
from pydantic import BaseModel, Field, ValidationError

# Canonical imports
from beta_pyramid_functional.B1_Kernel.SK_Engine.engine import ProjectCortex
from beta_pyramid_functional.B1_Kernel.contracts import TaskEnvelope, TaskStatus
from beta_pyramid_functional.B2_Orchestrator.llm_orchestrator import AgentOrchestrator, Provider
from beta_pyramid_functional.B3_SessionRegistry.session_models import AgentSession

logger = logging.getLogger("SynthesisAgent")

class ProposalType(str, Enum):
    REFACTOR = "refactor"
    PATCH = "patch"
    POLICY = "policy"
    SECURITY = "security"
    OPTIMIZE = "optimize"

class SynthesisProposal(BaseModel):
    """
    Structured architectural optimization proposal generated by Z9/Z14.
    """
    id: str = Field(default_factory=lambda: f"prop_{uuid.uuid4().hex[:6]}")
    type: ProposalType
    target_node: str
    rationale: str
    suggested_action: str
    confidence: float = Field(ge=0.0, le=1.0)
    impact: str = "medium"

class SynthesisAgent:
    """
    Z9/Z14 Meta-Optimizer.
    Analyzes ProjectCortex for architectural patterns and translates complex tasks
    using an ensemble of LLMs for high-reliability synthesis.
    """
    
    def __init__(self, report_dir: str = "beta_pyramid_functional/D_Interface/synthesis_reports"):
        self.report_dir = Path(report_dir)
        self.report_dir.mkdir(parents=True, exist_ok=True)
        self.threshold = 0.8  # Pattern similarity threshold

    async def translate_task(self, envelope: TaskEnvelope) -> Optional[SynthesisProposal]:
        """
        [TRINITY OPTIMIZATION]
        Uses concurrent LLM dispatch to translate a TaskEnvelope into a concrete SynthesisProposal.
        """
        logger.info(f"[SYNTHESIS] Translating task {envelope.task_id} via multi-LLM ensemble...")
        
        # 1. Prepare Sessions for Gemini and Ollama
        prompt = (
            f"As the EP-OS Synthesis Agent (Z9), translate this architectural goal into a structured JSON proposal.\n"
            f"TASK: {envelope.action} on {envelope.target_node}\n"
            f"INTENT: {envelope.intent or 'Structural Optimization'}\n"
            f"PAYLOAD: {json.dumps(envelope.payload)}\n\n"
            "Return EXCLUSIVELY a JSON object matching this schema:\n"
            '{"type": "patch|refactor|optimize", "target_node": "string", "rationale": "string", "suggested_action": "string", "confidence": 0.0-1.0}'
        )

        session_cloud = AgentSession(
            node_id="synthesis_cloud", node_z=9, task_title="Cloud Synthesis", 
            provider=Provider.GEMINI, task_context="Synthesis Mode"
        )
        session_cloud.add_user_message(prompt)

        session_local = AgentSession(
            node_id="synthesis_local", node_z=9, task_title="Local Synthesis", 
            provider=Provider.OLLAMA, task_context="Synthesis Mode"
        )
        session_local.add_user_message(prompt)

        # 2. Concurrent Dispatch
        try:
            results = await asyncio.gather(
                AgentOrchestrator.get_response(session_cloud),
                AgentOrchestrator.get_response(session_local),
                return_exceptions=True
            )
        except Exception as e:
            logger.error(f"[SYNTHESIS] Critical ensemble failure: {e}")
            return None

        # 3. Validation & Consensus
        proposals: List[SynthesisProposal] = []
        for res in results:
            if isinstance(res, str) and not res.startswith("["): # Check if it's a valid LLM response
                p = self._parse_proposal(res)
                if p: proposals.append(p)

        if not proposals:
            logger.warning("[SYNTHESIS] No valid proposals generated by ensemble.")
            return None

        # Consensus: Pick the one with highest confidence for now
        best_proposal = max(proposals, key=lambda x: x.confidence)
        logger.info(f"[SYNTHESIS] Proposal {best_proposal.id} accepted with confidence {best_proposal.confidence}")
        return best_proposal

    def _parse_proposal(self, text: str) -> Optional[SynthesisProposal]:
        """Robustly parses LLM text into a SynthesisProposal."""
        try:
            # Strip markdown and extract JSON
            clean = re.sub(r"```json|```", "", text).strip()
            # Simplistic JSON finding
            match = re.search(r"(\{.*\})", clean, re.DOTALL)
            if match:
                data = json.loads(match.group(1))
                return SynthesisProposal(**data)
        except Exception as e:
            logger.debug(f"[SYNTHESIS] Parse error: {e}")
        return None

    async def scan_and_synthesize(self) -> str:
        """
        Scan memory for patterns and generate a synthesis report.
        """
        cortex = await ProjectCortex.get_instance()
        sigs = {
            node_id: list(node.minhash_sig)
            for node_id, node in cortex.hypergraph.nodes.items()
            if getattr(node, "minhash_sig", None)
        }
        
        if not sigs:
            return "No memory blocks found for synthesis."
        
        clusters = self._cluster_signatures(sigs)
        
        report = {
            "timestamp": datetime.now().isoformat(),
            "analyzed_blocks": len(sigs),
            "patterns_discovered": len(clusters),
            "clusters": clusters
        }
        
        report_id = f"syn_{uuid.uuid4().hex[:8]}"
        report_path = self.report_dir / f"{report_id}.json"
        
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
            
        logger.info(f"Synthesis report generated: {report_id}")
        return report_id

    def _cluster_signatures(self, sigs: Dict[str, List[int]]) -> List[Dict[str, Any]]:
        """Identify clusters of highly similar memory blocks."""
        clusters = []
        visited = set()
        ids = list(sigs.keys())
        
        for i in range(len(ids)):
            id_a = ids[i]
            if id_a in visited:
                continue
                
            current_cluster = [id_a]
            visited.add(id_a)
            
            for j in range(i + 1, len(ids)):
                id_b = ids[j]
                if id_b in visited:
                    continue
                
                # Jaccard similarity between MinHash signatures
                sim = self._calculate_similarity(sigs[id_a], sigs[id_b])
                if sim >= self.threshold:
                    current_cluster.append(id_b)
                    visited.add(id_b)
            
            if len(current_cluster) > 1:
                clusters.append({
                    "cluster_id": f"pattern_{uuid.uuid4().hex[:6]}",
                    "member_count": len(current_cluster),
                    "members": current_cluster
                })
                
        return clusters

    @staticmethod
    def _calculate_similarity(sig1: List[int], sig2: List[int]) -> float:
        matches = sum(1 for a, b in zip(sig1, sig2) if a == b)
        return matches / len(sig1) if sig1 else 0.0
