import os
import json
from pathlib import Path
from typing import Dict, Any, Optional
import uuid

class NodeGenerator:
    """
    V8.0 Neural Autogenesis Engine.
    Scaffolds new nodes based on SynthesisProposals.
    """
    
    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir)

    def generate_node(self, node_id: str, title: str, z_level: int, sector: str, summary: str) -> str:
        """
        Scaffold a new node directory and manifest.
        """
        # Determine the sector folder
        sector_path = self.root_dir / "beta_pyramid_functional" / sector
        if not sector_path.exists():
            sector_path = self.root_dir / "beta_pyramid_functional" / "GREEN" # Fallback
            
        node_dir = sector_path / f"{z_level}_{node_id.upper()}"
        node_dir.mkdir(parents=True, exist_ok=True)
        
        # 1. Create Manifest
        manifest = {
            "id": node_id.lower(),
            "title": title,
            "z_level": z_level,
            "sector": sector,
            "coords": {"x": 5, "y": 5, "z": z_level},
            "layer_type": "beta",
            "kind": "autonomous_patch",
            "summary": summary,
            "state": "active",
            "canon_status": "runtime",
            "metadata": {
                "source": "neural-autogenesis",
                "parent_mission": "v8_baseline"
            }
        }
        
        with open(node_dir / ".node_manifest.json", "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
            
        # 2. Create Boilerplate Logic
        logic_code = f'"""\nAutonomous Node: {title}\nGenerated by Neural Autogenesis V8.0\n"""\n\nimport asyncio\n\nasync def run():\n    print("[{node_id.upper()}] Node active. Monitoring: {summary}")\n\nif __name__ == "__main__":\n    asyncio.run(run())\n'
        
        with open(node_dir / "index.py", "w", encoding="utf-8") as f:
            f.write(logic_code)
            
        return str(node_dir)
